"""
Report Generator Module
Generates a downloadable PDF summary report from the analysis results.
"""

from fpdf import FPDF
from datetime import datetime
import io


def sanitize_text(text: str) -> str:
    """Replace common unicode characters with their ASCII equivalents to prevent fpdf errors."""
    if not isinstance(text, str):
        return str(text)
    replacements = {
        '–': '-', '—': '-', '\u2013': '-', '\u2014': '-',
        '“': '"', '”': '"', '\u201c': '"', '\u201d': '"',
        '‘': "'", '’': "'", '\u2018': "'", '\u2019': "'",
        '…': '...', '\u2026': '...'
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    
    # Replace any remaining unmappable characters with '?'
    return text.encode('latin-1', 'replace').decode('latin-1')


def sanitize_data(data):
    """Recursively sanitize dictionary or list values for PDF rendering."""
    if isinstance(data, dict):
        return {k: sanitize_data(v) for k, v in data.items()}
    elif isinstance(data, list):
        return [sanitize_data(v) for v in data]
    elif isinstance(data, str):
        return sanitize_text(data)
    return data


class ERIAReport(FPDF):
    """Custom PDF class with ERIA branding and formatting."""

    def header(self):
        """Page header with ERIA branding."""
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(30, 58, 138)   # Deep blue
        self.cell(0, 10, "ERIA - Education Regulation Impact Analyzer", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(100, 100, 100)
        self.cell(0, 6, "AI-Powered Policy Analysis Report", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(4)
        self.set_draw_color(30, 58, 138)
        self.set_line_width(0.8)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(6)

    def footer(self):
        """Page footer with page number and timestamp."""
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        timestamp = datetime.now().strftime("%d %b %Y, %I:%M %p")
        self.cell(0, 10, f"Generated by ERIA | {timestamp} | Page {self.page_no()}", align="C")

    def section_title(self, title: str):
        """Render a styled section heading."""
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(30, 58, 138)
        self.set_fill_color(239, 246, 255)  # Light blue background
        self.cell(0, 8, f"  {title}", fill=True, new_x="LMARGIN", new_y="NEXT")
        self.ln(2)
        self.set_text_color(30, 30, 30)

    def body_text(self, text: str):
        """Render normal paragraph text."""
        self.set_font("Helvetica", "", 10)
        self.set_text_color(40, 40, 40)
        self.multi_cell(0, 6, str(text), new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def bullet_list(self, items: list):
        """Render a bulleted list."""
        self.set_font("Helvetica", "", 10)
        self.set_text_color(40, 40, 40)
        for item in items:
            item_text = sanitize_text(str(item))
            # Combine bullet and text into one multi_cell to avoid horizontal space bugs
            self.multi_cell(0, 6, chr(149) + "  " + item_text, new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def impact_badge(self, label: str, level: str, details: str):
        """Render a stakeholder impact row."""
        label = sanitize_text(str(label))
        level = sanitize_text(str(level))
        details = sanitize_text(str(details))
        
        level_colors = {
            "Positive":  (22, 163, 74),   # Green
            "Negative":  (220, 38,  38),  # Red
            "Mixed":     (217, 119, 6),   # Amber
            "Neutral":   (100, 116, 139), # Slate
        }
        color = level_colors.get(level, (100, 116, 139))

        self.set_font("Helvetica", "B", 10)
        self.set_text_color(40, 40, 40)
        self.write(7, label + ": ")

        self.set_font("Helvetica", "B", 10)
        self.set_text_color(*color)
        self.write(7, f"[{level}]  ")

        self.set_font("Helvetica", "", 9)
        self.set_text_color(60, 60, 60)
        self.write(7, details)
        self.ln(8)


def generate_pdf_report(analysis: dict) -> bytes:
    """
    Generate a formatted PDF report from the ERIA analysis dictionary.

    Args:
        analysis: The structured JSON analysis returned by the LLM analyzer

    Returns:
        bytes: PDF file content as bytes
    """
    # Clean all LLM output strings to prevent fpdf encoding errors
    analysis = sanitize_data(analysis)

    pdf = ERIAReport()
    pdf.set_margins(left=15, top=20, right=15)
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # ── Title Block ──────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(15, 23, 42)
    title = analysis.get("document_title", "Education Regulation Document")
    pdf.multi_cell(0, 9, title, align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(80, 80, 80)
    meta = (
        f"Issuing Body: {analysis.get('issuing_body', 'N/A')}  |  "
        f"Category: {analysis.get('topic_category', 'N/A')}  |  "
        f"Date: {analysis.get('regulation_date', 'N/A')}  |  "
        f"Risk Level: {analysis.get('risk_level', 'N/A')}"
    )
    pdf.cell(0, 7, meta, align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    # ── Summary ──────────────────────────────────────────────────────────────
    pdf.section_title("Executive Summary")
    pdf.body_text(analysis.get("summary", "No summary available."))

    # ── Purpose & Background ─────────────────────────────────────────────────
    pdf.section_title("Purpose & Background")
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(30, 58, 138)
    pdf.cell(0, 6, "Purpose:", new_x="LMARGIN", new_y="NEXT")
    pdf.body_text(analysis.get("purpose", "N/A"))

    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(30, 58, 138)
    pdf.cell(0, 6, "Historical Background:", new_x="LMARGIN", new_y="NEXT")
    pdf.body_text(analysis.get("background", "N/A"))

    # ── Stakeholder Impact ───────────────────────────────────────────────────
    pdf.section_title("Stakeholder Impact Analysis")
    stakeholder_map = analysis.get("stakeholder_impact", {})
    label_map = {
        "students": "Students",
        "faculty": "Faculty",
        "institutions": "Institutions",
        "administrators": "Administrators",
        "accreditation_teams": "Accreditation Teams",
    }
    for key, label in label_map.items():
        data = stakeholder_map.get(key, {})
        pdf.impact_badge(
            label,
            data.get("impact_level", "Neutral"),
            data.get("details", "No details available.")
        )

    # ── Impact Assessment ────────────────────────────────────────────────────
    pdf.section_title("Impact Assessment")
    impact = analysis.get("impact_assessment", {})
    for term, label in [
        ("short_term",  "Short-Term (0-1 Year)"),
        ("medium_term", "Medium-Term (1-5 Years)"),
        ("long_term",   "Long-Term (>5 Years)"),
    ]:
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(30, 58, 138)
        pdf.cell(0, 6, label + ":", new_x="LMARGIN", new_y="NEXT")
        pdf.bullet_list(impact.get(term, ["No data available."]))

    # ── Positives & Negatives ────────────────────────────────────────────────
    pdf.section_title("Positives & Negatives")
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(22, 163, 74)
    pdf.cell(0, 6, "Positives:", new_x="LMARGIN", new_y="NEXT")
    pdf.bullet_list(analysis.get("positives", []))

    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(220, 38, 38)
    pdf.cell(0, 6, "Negatives:", new_x="LMARGIN", new_y="NEXT")
    pdf.bullet_list(analysis.get("negatives", []))

    # ── Risks & Opportunities ────────────────────────────────────────────────
    pdf.section_title("Risks & Opportunities")
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(217, 119, 6)
    pdf.cell(0, 6, "Risks:", new_x="LMARGIN", new_y="NEXT")
    pdf.bullet_list(analysis.get("risks", []))

    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(30, 58, 138)
    pdf.cell(0, 6, "Opportunities:", new_x="LMARGIN", new_y="NEXT")
    pdf.bullet_list(analysis.get("opportunities", []))

    # ── Compliance Requirements ──────────────────────────────────────────────
    compliance = analysis.get("compliance_requirements", [])
    if compliance:
        pdf.section_title("Compliance Requirements")
        pdf.bullet_list(compliance)

    # ── Key Clauses ──────────────────────────────────────────────────────────
    key_clauses = analysis.get("key_clauses", [])
    if key_clauses:
        pdf.section_title("Key Clauses")
        pdf.bullet_list(key_clauses)

    # ── Chronology Notes ─────────────────────────────────────────────────────
    chronology = analysis.get("chronology_notes", "")
    if chronology:
        pdf.section_title("Chronology & Policy History")
        pdf.body_text(chronology)

    # ── Output as bytes ──────────────────────────────────────────────────────
    pdf_output = pdf.output()
    return bytes(pdf_output)
